version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5434:5432'
